### ISSUE TITLE
test with exported xml file throw exepction 

### ISSUE THREAD

**Issue by Hummel83** [gabbersepp/ib-flex-reader#2]
had you tested the file read function with a full xml file?

**Comment by gabbersepp** [comment]
Not yet. But I think this will produce exceptions. How should we handle them? 

I see two possibilities:

1. Ignore entries that can not be parsed to the specific contract due to missing enum values or other stuff.
2. return all those entries

The first one would be the worst solution I think. We should notice the developer about invalid entries. But I'm not sure what would be the best way.
